### ISSUE TITLE
excel.xls.to.list

### ISSUE THREAD

**Issue by EberSchmitz** [afcosta-ibm/ifm#7]
Padronizar:
1-os componentes das listas devem ser nomeadas usando a função names( )<-"nome"

**Comment by afcosta-ibm** [comment]
@EberSchmitz 
Solved with the code bellow:
`variables.list <- list(interest.rate = data.frame.interest.rate[[1]], activities = data.frame.activities[[1]], durations = data.frame.durations[[1]],predecessors = data.frame.predecessors, cash.flow.series = data.frame.cash.flow.series,graph.edges = edges)
`
